baseURL = 'https://stbo0013.stud.unixag.de/public/'
languageCode = 'de-de'
title = 'IoT Workshop'
theme = 'hugo-theme-learn'

[outputs]
home = [ "HTML", "RSS", "JSON"]

landingPageURL = "/iot-workshop-doc/"
landingPageName = "<i class='fas fa-home'></i> Home"